### ISSUE TITLE
CORS configuration missing api.mynixos.com

### ISSUE THREAD

**Issue by Elliot-Beaumont** [mynixos/support#12]
When attempting to update my username, a PUT and OPTIONS call is made to `api.mynixos.com` while I'm on `mynixos.com`.  The result is that the CORS configuration blocks the request since the hosts do not match.  Thus please add `api.mynixos.com` to the access-control-allow-origin section of the CORS configuration.

**Comment by pveierland** [comment]
Hi - I apologize for this being broken for so long! There was indeed a configuration issue of CORS for PUT specifically. This has now been fixed and should work as expected. Thank you for your report!
