### ISSUE TITLE
Broken colors in Create development shell > System list

### ISSUE THREAD

**Issue by imincik** [mynixos/support#2]
When I try to add `Development shell` in to my `Output` and try to add `System` the list of systems displays in broken looking colors.

See screenshot:
![screen-imincik-2023-02-01-10:00:45](https://user-images.githubusercontent.com/476346/215999106-0125e37d-8e66-4beb-b4ce-7d94da30119b.png)

My browser is Google Chrome Version 109.0.5414.74 (Official Build) (64-bit) from Nixpkgs.

**Comment by pveierland** [comment]
Thanks! Fix will be included in next release (v0.1.22).
